// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlscpjhisogytskmilkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsc2Nwamhpc29neXRza21pbGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDIyMTYsImV4cCI6MjA2MDkxODIxNn0.7zMdCKKkyuWSwlnOQpsUx7WIWeZb9Bz7atiPNY7NmTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);